### ISSUE TITLE
Quitar relación uno a muchos entre alerts y communities, ya que es una relación muchos a muchos y tiene una tabla en el medio

### ISSUE THREAD

**Issue by gmaggiw** [PD-FS/PignusCivitas_back#18]
Quitar relación uno a muchos entre alerts y communities, ya que es una relación muchos a muchos y tiene una tabla en el medio

**Comment by cmtoro** [comment]
Muy bien! :D

**Comment by cmtoro** [comment]
Se elimina relación entre alert y community
